config/routes.rb
Rails.application.routes.draw do

  resources :items
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: redirect('/items')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :count, :place, :price, :contact)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.slim
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :count
    = f.number_field :count
  .field
    = f.label :place
    = f.text_field :place
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :contact
    = f.text_field :contact
  .actions = f.submit

app/views/items/edit.html.slim
h1 Editing item

== render 'form'

=> link_to 'Show', @item
'|
=< link_to 'Back', items_path

app/views/items/index.html.slim
.container
    .col-md-12
      p 
        h2 ပစ္စည်း စာရင်း
      table.table.table-dark
        thead
          tr
            th = t :item_name
            th = t :stock_counts
            th = t :item_price
      
        tbody
          - @items.each do |item|
            tr
              td
                = link_to item.name, item_path(item)
              td = item.count
              td = item.price
      
      br
      
      = link_to 'New Item', new_item_path

app/views/items/new.html.slim
h1 New item

== render 'form'

= link_to 'Back', items_path

app/views/items/show.html.slim
p#notice = notice

.container
  .row
    .col-md-12
      h1 = @item.name
      
      table.table.table-dark
        thead
          tr
            th Name
            th Count
            th Place
            th Price
            th Contact
          tr
            th
              = @item.name
            th
              = @item.count
            th
              = @item.place
            th
              = @item.price
            th
              = @item.contact

=> link_to 'Edit', edit_item_path(@item)
'|
=< link_to 'Back', items_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Pyaesoneconstruction
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header 
      = render 'shared/header' 
    = yield

app/views/shared/_header.slim
nav.navbar.navbar-dark.bg-dark
  a.navbar-brand
    | Navbar
  // form.form-inline
  //   input.form-control.mr-sm-2[type="search" placeholder="Search" aria-label="Search"]
  //   button.btn.btn-outline-success.my-2.my-sm-0[type="submit"]
  //     | Search